### ISSUE TITLE
Encoding error on R 4.2 (devel)

### ISSUE THREAD

**Issue by lcolladotor** [r-lib/desc#118] opened 2021-11-23 02:55 UTC
Hi,

I'm encountering an error that I'm not 100% sure that is due to `desc`. It might be given the traceback information, hence why I'm reporting it here. But if belongs elsewhere, please let me know.

I'd appreciate you taking a look at this.

Thanks in advance!
Leo

## Error description

My GitHub Actions workflow for my `biocthis` package using the GitHub version of `pkgdown` errored out with 

```R
Error in iconv(mat[], from = "UTF-8", to = encoding) : 
  unsupported conversion from 'UTF-8' to 'Encoding: UTF-8'
```

at https://github.com/lcolladotor/biocthis/runs/4292895831?check_suite_focus=true#step:28:94. The traceback information https://github.com/lcolladotor/biocthis/runs/4292895831?check_suite_focus=true#step:28:88 shows that `base:::iconv(mat[], from = "UTF-8", to = encoding)` is involved after `desc$write(file = tf)`. `Encoding: UTF-8` likely comes from the `biocthis` DESCRIPTION at https://github.com/lcolladotor/biocthis/blob/0bbf986a2713a89012e5f85ce90b9f3101435ff6/DESCRIPTION#L16. 

## Locating the error source

The error is originated by https://github.com/lcolladotor/biocthis/blob/master/vignettes/biocthis.Rmd#L128 which uses several `usethis` functions https://github.com/lcolladotor/biocthis/blob/master/R/biocthis_example_pkg.R, in particular `usethis::create_package()` which uses `desc$write` at https://github.com/r-lib/usethis/blob/main/R/description.R#L71. `desc` in turn uses `base::iconv()` at https://github.com/r-lib/desc/blob/daece0e5816e17a461969489bfdda2d50b4f5fe5/R/description.R#L796.

## GHA runs

My GHA with R 4.2 (current devel) was using `desc` 1.4.0 https://github.com/lcolladotor/biocthis/runs/4292895831?check_suite_focus=true#step:21:71. The same code but with R 4.1 and the CRAN version of `pkgdown` did work https://github.com/lcolladotor/biocthis/runs/4293462431?check_suite_focus=true#step:21:70. 

| |  run 1 | run 2 |
| ---- | ---- | ---- |
| R session info | [GHA](https://github.com/lcolladotor/biocthis/runs/4292895831?check_suite_focus=true#step:21:71) | [GHA](https://github.com/lcolladotor/biocthis/runs/4293462431?check_suite_focus=true#step:21:70) |
| status | fails | runs |
| R | 4.2 (devel) | 4.1 |
| pkgdown | 1.9000.9000.9000 r-lib/pkgdown@e72fc30 | 1.6.1 |
| usethis | 2.1.3 | 2.1.3 |
| desc | 1.4.0 | 1.4.0 |

## Is it a `desc` issue with R 4.2 (devel)? 

Rather than this being a `pkgdown` issue, I'm guessing that maybe `desc` provides information that `base::iconv()` doesn't like anymore in R devel. But I'm not sure. I see that 20 days ago `desc` did pass all checks with R devel https://github.com/r-lib/desc/runs/4083193323?check_suite_focus=true. That would be after https://github.com/r-lib/desc/pull/112/commits/67d28126b13f44400134e9aa22e3ba9dde1ad4d0 which well, changed how `desc$write` works in relation to encoding.

Maybe this is not relevant since both GHA runs used `usethis` version 2.1.3. I see that `usethis` changed 2 months ago and started using `desc$write` from https://github.com/r-lib/usethis/blame/main/R/description.R#L71 at https://github.com/r-lib/usethis/commit/8b11a5f2ba49f03b5d43f099170475fa0caa68fc. Though also 21 days ago I see that it passed its tests on R devel https://github.com/r-lib/usethis/runs/4073956879?check_suite_focus=true.

**Comment by lcolladotor** [comment] 2021-11-23 03:39
Hmmm, I'm now less convinced this is related to `desc` itself. I installed R 4.2 on my computer and ran the offending line but didn't reproduce the error.

```R
> library(biocthis)
> pkgdir <- biocthis_example_pkg("biocthispkg", use_git = TRUE)
√ Creating 'C:/Users/fellg/AppData/Local/Temp/Rtmp4yHbtt/biocthispkg/'
√ Setting active project to 'C:/Users/fellg/AppData/Local/Temp/Rtmp4yHbtt/biocthispkg'
√ Creating 'R/'
√ Writing 'DESCRIPTION'
Package: biocthispkg
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * Leonardo Collado-Torres <lcolladotor@gmail.com> [aut, cre] (<https://orcid.org/0000-0003-2140-308X>)
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
    license
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
√ Writing 'NAMESPACE'
√ Initialising Git repo
√ Adding '.Rproj.user', '.Rhistory', '.Rdata', '.httr-oauth', '.DS_Store' to '.gitignore'
There are 3 uncommitted files:
* '.gitignore'
* 'DESCRIPTION'
* 'NAMESPACE'
Is it ok to commit them?

1: Not now
2: I agree
3: Negative

Selection: 2
√ Adding files
√ Making a commit with message 'Initial commit'
> options(width = 120)
> sessioninfo::session_info()
- Session info  ------------------------------------------------------------------------------------------------------
 hash: microphone, older person, smiling face

 setting  value
 version  R Under development (unstable) (2021-11-21 r81221)
 os       Windows 10 x64 (build 19042)
 system   x86_64, mingw32
 ui       Rgui
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/New_York
 date     2021-11-22
 pandoc   NA

- Packages -----------------------------------------------------------------------------------------------------------
 package     * version date (UTC) lib source
 askpass       1.1     2019-01-13 [1] CRAN (R 4.2.0)
 backports     1.3.0   2021-10-27 [1] CRAN (R 4.2.0)
 biocthis    * 1.5.0   2021-10-26 [1] Bioconductor
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.2.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.2.0)
 cli           3.1.0   2021-10-27 [1] CRAN (R 4.2.0)
 crayon        1.4.2   2021-10-29 [1] CRAN (R 4.2.0)
 credentials   1.3.1   2021-07-25 [1] CRAN (R 4.2.0)
 desc          1.4.0   2021-09-28 [1] CRAN (R 4.2.0)
 devtools    * 2.4.2   2021-06-07 [1] CRAN (R 4.2.0)
 digest        0.6.28  2021-09-23 [1] CRAN (R 4.2.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.2.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.2.0)
 gert          1.4.3   2021-11-10 [1] CRAN (R 4.2.0)
 glue          1.5.0   2021-11-07 [1] CRAN (R 4.2.0)
 knitr         1.36    2021-09-29 [1] CRAN (R 4.2.0)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.2.0)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.2.0)
 openssl       1.4.5   2021-09-02 [1] CRAN (R 4.2.0)
 pillar        1.6.4   2021-10-18 [1] CRAN (R 4.2.0)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.2.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
 pkgload       1.2.3   2021-10-13 [1] CRAN (R 4.2.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.2.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.2.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
 R.cache       0.15.0  2021-04-30 [1] CRAN (R 4.2.0)
 R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.2.0)
 R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.2.0)
 R.utils       2.11.0  2021-09-26 [1] CRAN (R 4.2.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 remotes       2.4.1   2021-09-29 [1] CRAN (R 4.2.0)
 rlang         0.4.12  2021-10-18 [1] CRAN (R 4.2.0)
 roxygen2      7.1.2   2021-09-08 [1] CRAN (R 4.2.0)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.2.0)
 rsthemes      0.3.1   2021-11-23 [1] Github (gadenbuie/rsthemes@bbe73ca)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.2.0)
 sessioninfo   1.2.1   2021-11-02 [1] CRAN (R 4.2.0)
 stringi       1.7.5   2021-10-04 [1] CRAN (R 4.2.0)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.2.0)
 styler        1.6.2   2021-09-23 [1] CRAN (R 4.2.0)
 sys           3.4     2020-07-23 [1] CRAN (R 4.2.0)
 testthat    * 3.1.0   2021-10-04 [1] CRAN (R 4.2.0)
 tibble        3.1.6   2021-11-07 [1] CRAN (R 4.2.0)
 usethis     * 2.1.3   2021-10-27 [1] CRAN (R 4.2.0)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.0)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.2.0)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.2.0)
 xfun          0.28    2021-11-04 [1] CRAN (R 4.2.0)
 xml2          1.3.2   2020-04-23 [1] CRAN (R 4.2.0)

 [1] C:/R/R-devel-bioc3.15/library

----------------------------------------------------------------------------------------------------------------------
```

**Comment by gaborcsardi** [comment] 2021-11-23 09:51
IDK how this could happen, expect if you set the `Encoding` field to `Encoding: UTF-8` accidentally. I don't see anything else in desc that would do this, and I also cannot reproduce this locally unfortunately.

**Comment by maelle** [comment] 2021-12-14 08:55
Getting the same error for github.com/ropensci/autotest https://github.com/r-universe/ropensci/runs/4511972414?check_suite_focus=true cc @mpadge @jeroen

**Comment by maelle** [comment] 2021-12-14 08:55
It does not happen when knitting the vignette, nor when running the code interactively, just when using pkgdown. :sweat_smile:

**Comment by maelle** [comment] 2021-12-14 09:20
If right before https://github.com/r-lib/usethis/blob/1bb32d7a32adae6a15263dc51de17d094ad40bae/R/description.R#L71 I add

```r
writeLines(print(desc$get("Encoding")), "/home/maelle/Documents/ropensci/usethis/blop")
```

and then run `pkgdown::build_articles("../autotest")`, in `blop.R` I get

```
[34mEncoding[39m: UTF-8
```
in that file. So some sort of cli usage issue?

If I create a package not from a pkgdown article, in `blop.R` I get the expected `UTF-8`.

**Comment by maelle** [comment] 2021-12-14 10:13
https://github.com/r-lib/pkgdown/blob/e72fc30f333dc4f50f3f9d1f274fc29d67e34974/R/rmarkdown.R#L37

**Comment by maelle** [comment] 2021-12-14 10:18
Reprex

```r
Sys.setenv("R_CLI_NUM_COLORS" = 256)
dir <- withr::local_tempdir(pattern = "encoding-yay")
usethis::create_package(dir, check_name = FALSE)
```

**Comment by maelle** [comment] 2021-12-14 10:21
Specifically things go "wrong" from `tidy_desc(desc)`

**Comment by maelle** [comment] 2021-12-14 10:22
More specifically, `desc$normalize()`

**Comment by maelle** [comment] 2021-12-14 10:25
Should https://github.com/r-lib/desc/blob/daece0e5816e17a461969489bfdda2d50b4f5fe5/R/str.R#L142 also set the environment variable?

**Comment by maelle** [comment] 2021-12-14 10:28
Actually even with the environment variable set in cli code priority is given to the option. :thinking:

**Comment by maelle** [comment] 2021-12-14 10:31
Smaller reprex

``` r
Sys.setenv("R_CLI_NUM_COLORS" = 256)
desc <- desc::desc("/home/maelle/Documents/ropensci/usethis")
desc$get("Encoding")
#> Encoding 
#>  "UTF-8"
desc$normalize()
desc$get("Encoding")
#>                          Encoding 
#> "\033[34mEncoding\033[39m: UTF-8"
```

<sup>Created on 2021-12-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by maelle** [comment] 2021-12-14 10:32
(yes a reprex with an absolute local path in it :see_no_evil: )

**Comment by maelle** [comment] 2021-12-14 10:38
With my branch in #121 I can build autotest articles (and my reprex looks ok).

**Comment by maelle** [comment] 2021-12-14 10:41
wait with desc GitHub version I do not get the error at all, even before my PR.

**Comment by maelle** [comment] 2021-12-14 10:42
This was fixed by https://github.com/r-lib/desc/commit/daece0e5816e17a461969489bfdda2d50b4f5fe5 :grin:

**Comment by lcolladotor** [comment] 2021-12-17 17:49
Cool, thanks @maelle for the info!

**Closed** 2021-12-17 17:49 UTC
Labels: reprex
